services:
  - type: web
    name: n8n
    env: docker
    plan: free
    envVars:
      - key: N8N_BASIC_AUTH_USER
        value: pravin@workflow.com
      - key: N8N_BASIC_AUTH_PASSWORD
        value: Gabriel@2604
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 5678
      - key: N8N_EDITOR_BASE_URL
        value: https://n8n-render-v9rx.onrender.com
      - key: WEBHOOK_URL
        value: https://n8n-render-v9rx.onrender.com
